name: Python CI Workflow

on:
  push:
    branches:
      - master
      - release
  pull_request:
    branches:
      - master
      - release
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      FULL_NAME: "Мажейкин Александр"
      GROUP_NUMBER: "M3113"

    steps:
    - name: Print Personal Info
      run: |
        echo "Full Name: $FULL_NAME"
        echo "Group Number: $GROUP_NUMBER"
        echo "GitHub Username: ${{ github.actor }}"

    - name: Set up Python 3.13
      uses: actions/setup-python@v4
      with:
        python-version: 3.13

    - name: Install dependencies
      run: |
        cd $GITHUB_WORKSPACE
        python -m pip install -r requirements.txt

    - name: Run unit tests
      run: |
        python -m unittest discover -s tests -p "*.py"

    - name: Lint code with flake8
      run: |
        pip install flake8
        flake8 .

    - name: Format code with black
      run: |
        pip install black
        black .
